# Generated by Django 5.0.4 on 2024-05-16 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_candidato_tel_remove_datore_tel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.CharField(max_length=30, null=True)),
                ('residenza', models.CharField(max_length=30, null=True)),
                ('competenze', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='id_candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_candidatura', to='myapp.utente'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='id_candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_messaggio', to='myapp.utente'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='id_datore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datore_messaggio', to='myapp.utente'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='id_datore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datore_offerta', to='myapp.utente'),
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='Datore',
        ),
    ]
