# Generated by Django 5.0.4 on 2024-05-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_offerta_luogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='impiego',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='stipendio',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
