# Generated by Django 5.0.4 on 2024-05-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_offerta_impiego_offerta_stipendio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='id_candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_candidatura', to='myapp.utente'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='id_offerta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerta_candidatura', to='myapp.offerta'),
        ),
        migrations.CreateModel(
            name='Preferiti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_preferiti', to='myapp.utente')),
                ('id_offerta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerta_preferiti', to='myapp.offerta')),
            ],
        ),
    ]
