# Generated by Django 5.0.4 on 2024-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_candidatura_id_candidato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggio',
            name='contenuto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='descrizione',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='requisiti',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='competenze',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
