# Generated by Django 5.0.4 on 2024-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_messaggio_contenuto_alter_offerta_descrizione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggio',
            name='contenuto',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
