# Generated by Django 5.0.4 on 2024-05-31 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_messaggio_contenuto'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggio',
            name='candidatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatura_messaggio', to='myapp.candidatura'),
        ),
    ]
